# Generated by Django 2.0.7 on 2018-07-18 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 7, 43, 28, 152378)),
        ),
    ]
